In [137]:
import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt
from sklearn import tree

In [138]:
dataset = pd.read_csv("input.csv")

In [139]:
dataset

Realistic  Investigate  Artistic  Social  Enterprising  Conventional  \
0            3            2         3       1             4             4   
1            5            7         6       3             2             6   
2            4            3         2       4             2             4   
3            4            0         1       6             4             6   
4            4            4         1       2             1             4   
..         ...          ...       ...     ...           ...           ...   
495          4            3         3       4             4             3   
496          4            3         3       4             3             5   
497          4            3         3       4             5             3   
498          4            3         3       4             3             5   
499          4            3         3       4             3             5   

     Linguistic  Logical-mathematical  Spatial  Bodily-Kinesthetic  Musical  \
0             4                     5        5                   5        6   
1             1                     1        2                   1        1   
2             4                     4        4                   3        2   
3             2                     3        4                   5        3   
4             2                     6        5                   1        5   
..          ...                   ...      ...                 ...      ...   
495           7                     3        4                   5        3   
496           4                     5        3                   3        2   
497           4                     5        3                   3        2   
498           7                     5        3                   5        3   
499           2                     6        3                   5        8   

     Interpersonal  Intrapersonal  Naturalistic  MATH  ENG  SCI  SOC-SCI  \
0                3              5             6    86   81   84       87   
1                2              1             3    90   90   88       87   
2                1              5             4    92   91   89       89   
3                5              6             3    90   92   91       90   
4                3              2             3    92   90   89       88   
..             ...            ...           ...   ...  ...  ...      ...   
495              5              4             3    85   90   86       88   
496              3              4             2    85   90   86       88   
497              3              4             2    94   97   91       95   
498              4              2             3    84   93   91       96   
499              2              4             4    88   93   92       86   

     CLASS  
0        1  
1        1  
2        1  
3        1  
4        1  
..     ...  
495      4  
496      4  
497      4  
498      4  
499      4  

[500 rows x 19 columns]

In [140]:
riasec = ["Realistic", "Investigate", "Artistic", "Social", "Enterprising", "Conventional"]
learning_style = ["Linguistic", "Logical-mathematical", "Spatial", "Bodily-Kinesthetic", "Musical", "Interpersonal", "Intrapersonal", "Naturalistic",]

In [141]:
dataset[riasec] = dataset[riasec]/7 *100
dataset[learning_style] = dataset[learning_style]/8 *100

In [142]:
X = dataset.iloc[:, 0:18]
y = dataset.iloc[:, 18]

In [143]:
X

Realistic  Investigate   Artistic     Social  Enterprising  Conventional  \
0    42.857143    28.571429  42.857143  14.285714     57.142857     57.142857   
1    71.428571   100.000000  85.714286  42.857143     28.571429     85.714286   
2    57.142857    42.857143  28.571429  57.142857     28.571429     57.142857   
3    57.142857     0.000000  14.285714  85.714286     57.142857     85.714286   
4    57.142857    57.142857  14.285714  28.571429     14.285714     57.142857   
..         ...          ...        ...        ...           ...           ...   
495  57.142857    42.857143  42.857143  57.142857     57.142857     42.857143   
496  57.142857    42.857143  42.857143  57.142857     42.857143     71.428571   
497  57.142857    42.857143  42.857143  57.142857     71.428571     42.857143   
498  57.142857    42.857143  42.857143  57.142857     42.857143     71.428571   
499  57.142857    42.857143  42.857143  57.142857     42.857143     71.428571   

     Linguistic  Logical-mathematical  Spatial  Bodily-Kinesthetic  Musical  \
0          50.0                  62.5     62.5                62.5     75.0   
1          12.5                  12.5     25.0                12.5     12.5   
2          50.0                  50.0     50.0                37.5     25.0   
3          25.0                  37.5     50.0                62.5     37.5   
4          25.0                  75.0     62.5                12.5     62.5   
..          ...                   ...      ...                 ...      ...   
495        87.5                  37.5     50.0                62.5     37.5   
496        50.0                  62.5     37.5                37.5     25.0   
497        50.0                  62.5     37.5                37.5     25.0   
498        87.5                  62.5     37.5                62.5     37.5   
499        25.0                  75.0     37.5                62.5    100.0   

     Interpersonal  Intrapersonal  Naturalistic  MATH  ENG  SCI  SOC-SCI  
0             37.5           62.5          75.0    86   81   84       87  
1             25.0           12.5          37.5    90   90   88       87  
2             12.5           62.5          50.0    92   91   89       89  
3             62.5           75.0          37.5    90   92   91       90  
4             37.5           25.0          37.5    92   90   89       88  
..             ...            ...           ...   ...  ...  ...      ...  
495           62.5           50.0          37.5    85   90   86       88  
496           37.5           50.0          25.0    85   90   86       88  
497           37.5           50.0          25.0    94   97   91       95  
498           50.0           25.0          37.5    84   93   91       96  
499           25.0           50.0          50.0    88   93   92       86  

[500 rows x 18 columns]

In [149]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [150]:
#from sklearn.preprocessing import StandardScaler

#sc = StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)

In [151]:
from sklearn.ensemble import RandomForestClassifier

regressor = RandomForestClassifier(n_estimators=100, criterion='gini', max_depth=5, random_state=0)
regressor.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, random_state=0)

In [152]:
y_pred = regressor.predict(X_test)

In [153]:
#print(y_pred)

In [155]:
#FEATURE IMPORTANCE

In [156]:
feature_list = list(X.columns)
feature_imp = pd.Series(regressor.feature_importances_, index=feature_list).sort_values(ascending=False)

In [157]:
print(feature_imp)

Bodily-Kinesthetic      0.146093
Realistic               0.121879
Intrapersonal           0.118317
ENG                     0.085783
Investigate             0.077421
Linguistic              0.072531
Logical-mathematical    0.052110
Artistic                0.049757
Spatial                 0.046513
Musical                 0.040871
SOC-SCI                 0.031667
Enterprising            0.030817
Social                  0.030518
Naturalistic            0.026015
MATH                    0.023548
Interpersonal           0.022063
SCI                     0.018208
Conventional            0.005890
dtype: float64


In [158]:
#CONFUSION MATRIX

In [159]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[29  1  2  4]
 [ 0 38  0  0]
 [ 0  0 39  0]
 [ 0  7  0 30]]
              precision    recall  f1-score   support

           1       1.00      0.81      0.89        36
           2       0.83      1.00      0.90        38
           3       0.95      1.00      0.97        39
           4       0.88      0.81      0.85        37

    accuracy                           0.91       150
   macro avg       0.91      0.90      0.90       150
weighted avg       0.91      0.91      0.91       150

0.9066666666666666


In [104]:
#filename = 'random_forest_model.sav'
#pickle.dump(regressor, open(filename, 'wb'))


In [46]:
fn=np.array(dataset.columns[:-1])
cn=["STEM", "HUMSS", "ABM", "GAS"]

fig, axes = plt.subplots(nrows = 1,ncols = 1,figsize = (10,10), dpi=1020)
tree.plot_tree(regressor.estimators_[0],
               feature_names = fn, 
               class_names=cn,
               max_depth=5,
               filled = True);
fig.savefig('rf_individualtree.png')

In [1]:
#fn=np.array(dataset.columns[:-1])
#cn=["STEM", "HUMSS", "ABM", "GAS"]

#fig, axes = plt.subplots(nrows = 1,ncols = 5,figsize = (10,2), dpi=900)
#for index in range(0, 5):
#    tree.plot_tree(regressor.estimators_[index],
#                   feature_names = fn, 
#                   class_names=cn,
#                   filled = True,
#                   max_depth=5,
#                   ax = axes[index]);

#    axes[index].set_title('Estimator: ' + str(index), fontsize = 11)
#fig.savefig('rf_5trees.png')