In [1]:
import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt
from sklearn import tree

In [2]:
dataset = pd.read_csv("input.csv")

In [3]:
dataset

Realistic  Investigate  Artistic  Social  Enterprising  Conventional  \
0            3            2         3       1             4             4   
1            5            7         6       3             2             6   
2            4            3         2       4             2             4   
3            4            0         1       6             4             6   
4            4            4         1       2             1             4   
..         ...          ...       ...     ...           ...           ...   
495          4            3         3       4             4             3   
496          4            3         3       4             3             5   
497          4            3         3       4             5             3   
498          4            3         3       4             3             5   
499          4            3         3       4             3             5   

     Linguistic  Logical-mathematical  Spatial  Bodily-Kinesthetic  Musical  \
0             4                     5        5                   5        6   
1             1                     1        2                   1        1   
2             4                     4        4                   3        2   
3             2                     3        4                   5        3   
4             2                     6        5                   1        5   
..          ...                   ...      ...                 ...      ...   
495           7                     3        4                   5        3   
496           4                     5        3                   3        2   
497           4                     5        3                   3        2   
498           7                     5        3                   5        3   
499           2                     6        3                   5        8   

     Interpersonal  Intrapersonal  Naturalistic  MATH  ENG  SCI  SOC-SCI  \
0                3              5             6    86   81   84       87   
1                2              1             3    90   90   88       87   
2                1              5             4    92   91   89       89   
3                5              6             3    90   92   91       90   
4                3              2             3    92   90   89       88   
..             ...            ...           ...   ...  ...  ...      ...   
495              5              4             3    85   90   86       88   
496              3              4             2    85   90   86       88   
497              3              4             2    94   97   91       95   
498              4              2             3    84   93   91       96   
499              2              4             4    88   93   92       86   

     CLASS  
0        1  
1        1  
2        1  
3        1  
4        1  
..     ...  
495      4  
496      4  
497      4  
498      4  
499      4  

[500 rows x 19 columns]

In [4]:
riasec = ["Realistic", "Investigate", "Artistic", "Social", "Enterprising", "Conventional"]
learning_style = ["Linguistic", "Logical-mathematical", "Spatial", "Bodily-Kinesthetic", "Musical", "Interpersonal", "Intrapersonal", "Naturalistic",]

In [5]:
dataset[riasec] = dataset[riasec]/7 *100
dataset[learning_style] = dataset[learning_style]/8 *100

In [6]:
X = dataset.iloc[:, 0:18].values
y = dataset.iloc[:, 18].values

In [7]:
X

array([[ 42.85714286,  28.57142857,  42.85714286, ...,  81.        ,
         84.        ,  87.        ],
       [ 71.42857143, 100.        ,  85.71428571, ...,  90.        ,
         88.        ,  87.        ],
       [ 57.14285714,  42.85714286,  28.57142857, ...,  91.        ,
         89.        ,  89.        ],
       ...,
       [ 57.14285714,  42.85714286,  42.85714286, ...,  97.        ,
         91.        ,  95.        ],
       [ 57.14285714,  42.85714286,  42.85714286, ...,  93.        ,
         91.        ,  96.        ],
       [ 57.14285714,  42.85714286,  42.85714286, ...,  93.        ,
         92.        ,  86.        ]])

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [9]:
#from sklearn.preprocessing import StandardScaler

#sc = StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)

#X_train

In [10]:
from sklearn.ensemble import RandomForestClassifier

regressor = RandomForestClassifier(n_estimators=100, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

In [11]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[29  0  3  4]
 [ 0 38  0  0]
 [ 0  0 39  0]
 [ 0  5  0 32]]
              precision    recall  f1-score   support

           1       1.00      0.81      0.89        36
           2       0.88      1.00      0.94        38
           3       0.93      1.00      0.96        39
           4       0.89      0.86      0.88        37

    accuracy                           0.92       150
   macro avg       0.93      0.92      0.92       150
weighted avg       0.92      0.92      0.92       150

0.92


In [12]:
#filename = 'random_forest_model.sav'
#pickle.dump(regressor, open(filename, 'wb'))


In [14]:
fn=np.array(dataset.columns[:-1])
cn=["STEM", "HUMSS", "ABM", "GAS"]

fig, axes = plt.subplots(nrows = 1,ncols = 1,figsize = (10,10), dpi=1020)
tree.plot_tree(regressor.estimators_[0],
               feature_names = fn, 
               class_names=cn,
               filled = True);
fig.savefig('rf_individualtree.png')

In [17]:
#fn=np.array(dataset.columns[:-1])
#cn=["STEM", "HUMSS", "ABM", "GAS"]

#fig, axes = plt.subplots(nrows = 1,ncols = 5,figsize = (10,2), dpi=900)
#for index in range(0, 5):
#    tree.plot_tree(regressor.estimators_[index],
#                   feature_names = fn, 
#                   class_names=cn,
#                   filled = True,
#                   ax = axes[index]);
#    
#    axes[index].set_title('Estimator: ' + str(index), fontsize = 11)
#fig.savefig('rf_5trees.png')