In [1]:
import pandas as pd
import numpy as np
import pickle

In [2]:
dataset = pd.read_csv("input.csv")

In [3]:
dataset

Realistic  Investigate  Artistic  Social  Enterprising  Conventional  \
0            3            2         3       1             4             4   
1            5            7         6       3             2             6   
2            4            3         2       4             2             4   
3            4            0         1       6             4             6   
4            4            4         1       2             1             4   
..         ...          ...       ...     ...           ...           ...   
495          4            3         3       4             4             3   
496          4            3         3       4             3             5   
497          4            3         3       4             5             3   
498          4            3         3       4             3             5   
499          4            3         3       4             3             5   

     Linguistic  Logical-mathematical  Spatial  Bodily-Kinesthetic  Musical  \
0             4                     5        5                   5        6   
1             1                     1        2                   1        1   
2             4                     4        4                   3        2   
3             2                     3        4                   5        3   
4             2                     6        5                   1        5   
..          ...                   ...      ...                 ...      ...   
495           7                     3        4                   5        3   
496           4                     5        3                   3        2   
497           4                     5        3                   3        2   
498           7                     5        3                   5        3   
499           2                     6        3                   5        8   

     Interpersonal  Intrapersonal  Naturalistic  MATH  ENG  SCI  SOC-SCI  \
0                3              5             6    86   81   84       87   
1                2              1             3    90   90   88       87   
2                1              5             4    92   91   89       89   
3                5              6             3    90   92   91       90   
4                3              2             3    92   90   89       88   
..             ...            ...           ...   ...  ...  ...      ...   
495              5              4             3    85   90   86       88   
496              3              4             2    85   90   86       88   
497              3              4             2    94   97   91       95   
498              4              2             3    84   93   91       96   
499              2              4             4    88   93   92       86   

     CLASS  
0        1  
1        1  
2        1  
3        1  
4        1  
..     ...  
495      4  
496      4  
497      4  
498      4  
499      4  

[500 rows x 19 columns]

In [4]:
riasec = ["Realistic", "Investigate", "Artistic", "Social", "Enterprising", "Conventional"]
learning_style = ["Linguistic", "Logical-mathematical", "Spatial", "Bodily-Kinesthetic", "Musical", "Interpersonal", "Intrapersonal", "Naturalistic",]

In [5]:
dataset[riasec] = dataset[riasec]/7 *100
dataset[learning_style] = dataset[learning_style]/8 *100

In [6]:
X = dataset.iloc[:, 0:18].values
y = dataset.iloc[:, 18].values

In [7]:
X.shape

(500, 18)

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

X_train

array([[ 0.3275765 ,  0.83333789,  1.41128273, ...,  1.46782107,
        -0.79990859,  1.57845272],
       [-1.52164566, -0.42929528, -1.08340897, ..., -0.91749466,
        -0.39995429, -0.7926136 ],
       [-0.90523827, -0.42929528, -0.45973604, ...,  0.27516321,
        -1.59981717, -0.45388984],
       ...,
       [ 0.94398388,  1.46465447, -1.08340897, ..., -0.61933019,
         0.79990859, -0.45388984],
       [-1.52164566, -1.06061186,  2.65862858, ..., -0.02300126,
         0.        , -0.11516608],
       [ 0.3275765 , -1.06061186,  0.78760981, ...,  1.76598554,
        -0.39995429,  1.57845272]])

In [10]:
from sklearn.ensemble import RandomForestClassifier

regressor = RandomForestClassifier(n_estimators=100, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

In [54]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[30  0  2  4]
 [ 0 38  0  0]
 [ 0  0 39  0]
 [ 0  5  0 32]]
              precision    recall  f1-score   support

           1       1.00      0.83      0.91        36
           2       0.88      1.00      0.94        38
           3       0.95      1.00      0.97        39
           4       0.89      0.86      0.88        37

    accuracy                           0.93       150
   macro avg       0.93      0.92      0.92       150
weighted avg       0.93      0.93      0.93       150

0.9266666666666666


In [55]:
filename = 'random_forest_model.sav'
pickle.dump(regressor, open(filename, 'wb'))


In [56]:
pickle.dump(sc, open('scaler.pkl','wb'))