In [5]:
import pandas as pd
import numpy as np
import pickle

In [6]:
dataset = pd.read_csv("out.csv")

In [7]:
dataset

Realistic  Investigate  Artistic  Social  Enterprising  Conventional  \
0            1            0         0       1             0             1   
1            1            1         0       0             0             1   
2            0            1         1       0             0             1   
3            0            1         0       0             1             1   
4            0            0         1       1             0             1   
..         ...          ...       ...     ...           ...           ...   
495          1            0         0       1             0             1   
496          0            0         1       1             1             0   
497          1            0         0       1             0             1   
498          1            0         0       1             0             1   
499          1            1         0       0             1             0   

     Naturalist  Spatial  Linguistic  Intrapersonal  Bodily-Kinesthetic  \
0             1        0           1              1                   0   
1             0        1           0              1                   0   
2             0        1           0              1                   0   
3             0        1           0              1                   0   
4             1        1           0              0                   0   
..          ...      ...         ...            ...                 ...   
495           1        0           1              1                   0   
496           0        0           1              1                   0   
497           0        1           1              0                   0   
498           1        0           1              1                   0   
499           0        1           1              0                   0   

     Musical  Logical-mathematical  Interpersonal  Math  English  Science  \
0          0                     0              0    89       87       88   
1          0                     1              0    90       89       91   
2          1                     0              0    92       98       89   
3          0                     1              0    92       90       91   
4          1                     0              0    91       93       93   
..       ...                   ...            ...   ...      ...      ...   
495        0                     0              0    89       92       82   
496        0                     1              0    94       98       91   
497        0                     0              1    94       89       89   
498        0                     0              0    94       89       89   
499        0                     1              1    92       90       89   

     Social Science  Class  
0                87      4  
1                88      1  
2                96      2  
3                89      1  
4                87      2  
..              ...    ...  
495              90      4  
496              95      2  
497              89      4  
498              89      4  
499              92      3  

[500 rows x 19 columns]

In [8]:
X = dataset.iloc[:, 0:18].values
y = dataset.iloc[:, 18].values

In [9]:
X.shape

(500, 18)

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

X_train





array([[-1.040833  , -1.01149463,  1.52752523, ..., -0.62897498,
        -0.04818094, -0.14078673],
       [ 0.96076892, -1.01149463, -0.65465367, ..., -0.05717954,
        -0.44035141, -0.80666989],
       [ 0.96076892,  0.98863599, -0.65465367, ...,  0.80051361,
         0.34398952, -1.13961148],
       ...,
       [-1.040833  ,  0.98863599, -0.65465367, ..., -0.05717954,
        -0.83252187, -0.80666989],
       [ 0.96076892, -1.01149463, -0.65465367, ..., -0.05717954,
         0.34398952,  0.19215486],
       [ 0.96076892, -1.01149463, -0.65465367, ...,  1.65820677,
         1.12833045,  1.85686277]])

In [12]:
from sklearn.ensemble import RandomForestClassifier

regressor = RandomForestClassifier(n_estimators=100, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

In [13]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[37  0  1  2]
 [ 0 40  1  0]
 [ 0  1 36  0]
 [ 0  3  0 29]]
              precision    recall  f1-score   support

           1       1.00      0.93      0.96        40
           2       0.91      0.98      0.94        41
           3       0.95      0.97      0.96        37
           4       0.94      0.91      0.92        32

    accuracy                           0.95       150
   macro avg       0.95      0.94      0.95       150
weighted avg       0.95      0.95      0.95       150

0.9466666666666667


In [14]:
filename = 'random_forest_model.sav'
pickle.dump(regressor, open(filename, 'wb'))


In [15]:
pickle.dump(sc, open('scaler.pkl','wb'))